version: '3.2'

services:
  node:
    build: ./
    networks:
      - Mexico_Lindo_Contigo
    environment:
      #General
      - TOKEN=pwonTvTjYv9RjzujOZ8OE1erQPLZSjfM
      - WEB_APP_URL_PRODUCTION=https://wrong-powder.com/
      - WEB_APP_URL_DEVELOP=http://localhost:3000/
      #DB Config
      - HOST=mlc-mysql-api
      - MYSQL_USER=graymarrow
      - MYSQL_PASS=Sh0r3sofPl3nty
      - MYSQL_DB=MLC_Db
    volumes: 
      - .:/usr/src/
      - /usr/src/node_modules/
    container_name: mlc-nodejs-api
    ports:
      - 3000:3000
      - 80:80
      - 443:443
  mysql:
    image: mysql:8.0.21
    cap_add:
      - SYS_NICE
    networks:
      - Mexico_Lindo_Contigo
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=graymarrow
      - MYSQL_PASSWORD=Sh0r3sofPl3nty
      - MYSQL_DATABASE=MLC_Db
    volumes:
      - /Sequelize/MySQL:/docker-entrypoint-initdb.d
    container_name: mlc-mysql-api
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.6
    depends_on:
      - mysql
    networks:
      - Mexico_Lindo_Contigo
    ports:
      - "3001:80"
    environment:
      - PMA_HOST=mlc-mysql-api
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: mlc-phpmyadmin-api
networks:
  Mexico_Lindo_Contigo: